@startuml Account Management And Login
title Activity Diagram - Kelola Pengguna
|actor1|Administrator
|Sistem|Sistem
|actor2|Pengguna

|actor1|
start
:Membuka halaman pengguna;

|Sistem|
:Menampilkan daftar pengguna;

|actor1|
:Melihat daftar pengguna;
split
    :Tambah;
split again
    :Ubah;
split again
    :Hapus;
end split

|Sistem|
:Menyimpan;

|actor1|
:Menyerahkan akun pengguna;

|actor2|
:Login;

|Sistem|
:Sistem verifikasi kredensial pengguna;
if (kredensial valid?) then (tidak)
|Sistem|
:Akses ditolak;
kill

else (ya)
|actor2|
:Dapat akses aplikasi;

stop
@enduml