@startuml Mengelola data barang
|actor1|Pegawai/Admin
start
:Memilih form barang\nmasuk atau keluar;
:Input barang\n masuk/keluar;

|Sistem|
:Menyimpan transaksi \ndan mengubah jumlah stok;

|actor1|
:Membuka riwayat transaksi;

|Sistem|
:Menampilkan data\n transaksi barang\n keluar/masuk;

' |actor1|
' :Menekan tombol\n download spreadsheet;

' |Sistem|
' :Download data data transaksi;

|actor1|
:Membuka halaman home;

|Sistem|
:Menampilkan kumpulan\n data statistik dari\n stok dan transaksi;


stop
@enduml
