@startuml Activity Diagram - Pengaturan
title Activity Diagram - Pengaturan
|actor1|Administrator
|Sistem|
start
|actor1|
:Membuka halaman pengaturan;
:Mengubah pengaturan;
:Tekan simpan;

|Sistem|
:Menyimpan pengaturan;
:Menampilkan pesan sukses;

|actor1|
:Melihat pesan sukses;

stop
@enduml