@startuml manajemen akun dan login
actor Admin as actor1
actor "Admin-lain\nPegawai\nDirektur" as actor2
participant "Halaman\nKelola Pengguna" as accountManagement
participant "Halaman\nLogin" as login
participant Sistem as system
database Pengguna as users

actor1 -> accountManagement: Membuka kelola pengguna
activate actor1
activate accountManagement
accountManagement -> system: Permintaan daftar pengguna
activate system
system -> users: Mengambil data pengguna
activate users
return Data pengguna
return Daftar pengguna
return Melihat daftar pengguna

actor1 -> accountManagement: Input data pengguna baru
activate accountManagement
accountManagement -> system: Pengguna baru
activate system
system -> users: Simpan pengguna baru
activate users
return Pengguna baru
return Akun pengguna baru
return Akun Pengguna baru

actor1 -> actor2: Penyerahan akun
activate actor2
actor2 -> login: Input kredensial akun
activate login
login -> system: Kredensial akun
activate system
system -> users: Ambil data pengguna
activate users
return Data pengguna
system -> system : Verifikasi pengguna
alt Login gagal
login <-- system: Pesan gagal
actor2 <-- login: Pemberitahuan gagal
else Login sukses
return Akses sistem
return Akses sistem
return Pengguna mengakses\nsistem sesuai role yang\n diberikan
end

@enduml