@startuml Pengelolaan barang

actor "Admin/Pegawai" as actor1
participant "Form Barang\n Keluar/Masuk" as form
participant "Riwayat Transaksi" as history
participant "Home" as home
participant Sistem as sistem
database "Transaksi" as db2
database "Barang" as db1

activate actor1
actor1 -> form: input barang keluar/masuk
activate form
form -> sistem: barang keluar/masuk
activate sistem
sistem -> db2: simpan transaksi
activate db2
return berhasil
sistem -> db1: kurangi/tambah stok
activate db1
return berhasil
return notifikasi berhasil
return notifikasi berhasil

actor1 -> history: Membuka riwayat transaksi
activate history
history -> sistem: Meminta transaksi
activate sistem
sistem -> db2: Mengambil transaksi
activate db2
return data transaksi
return data transaksi
return Menampilkan data transaksi

actor1 -> home: Membuka halaman home
activate home
home -> sistem: Meminta data statistik
activate sistem
sistem -> db2: Mengambil transaksi
activate db2
return Transaksi
sistem -> db1: Mengambil barang
activate db1
return Barang
sistem -> sistem: Menghitung statistik
return Data statistik
return Menampilkan statistik

@enduml