@startuml Laporan
title Sequence Diagram - Laporan

actor "Petugas" as actor1
participant "Halaman Laporan" as laporan
participant "Server" as sistem
database "Database" as db

actor1 -> laporan: Memilih jenis laporan pada menu
activate laporan

laporan -> sistem: Request laporan
activate sistem
sistem -> db: Query data laporan
activate db
db --> sistem: Data laporan
deactivate db
sistem --> laporan: Data laporan
deactivate sistem
' laporan --> actor1: Tampilkan laporan

actor1 -> laporan: Klik unduh laporan
laporan -> sistem: Permintaan file laporan
activate sistem
sistem -> db: Query data file laporan
activate db
db --> sistem: Data laporan
deactivate db
sistem --> laporan: File laporan
deactivate sistem
laporan --> actor1: File laporan (unduh)
deactivate laporan

@enduml