@startuml setting
title Sequence Diagram - Pengaturan
actor Administrator as actor1
participant "Halaman Setting" as setting
participant Sistem as sistem
database "Database" as db

activate actor1
actor1 -> setting: ubah setting
activate setting
setting -> sistem: perubahan setting
activate sistem
sistem -> db: menyimpan perubahan
activate db
return settingan diperbarui
return tampilkan setting terbaru
return tampilkan setting terbaru
@enduml