---
title: Sistem Berjalan pencatatan barang di unit ATK RSUD Haji Darlan Ismail
config:
  theme: default    
---
flowchart TD
    START 
    --> process1 
    --> input1 
    --> process2 
    --> input2
    --> END

    START((Mulai))
    process1[Pencarian lembar register yang sesuai]
    input1[/Pencatatan barang keluar/masuk/]
    process2[Menghitung stok]
    input2[/Mencatat stok/]
    END((AKHIR))