@startuml class

enum "Peran" as role {
+id: UUID
+nama: String
--
tugaskan_ke_pengguna()
}

class "Pengguna" as user {
+id: UUID
+nama: String
+username: String
-password: String
+peran_id: UUID
+url_photo_profil: String
--
+tambah()
+update()
+hapus()
}

class "Satuan Ukuran" as unit {
+id: UUID
+nama: String
+apakah_satuan_dasar: Boolean
+konversi: Integer
+satuan_dasar_id: UUID
--
+tambah()
+update()
+hapus()
+dapatkan_konversi_dengan_satuan_id()
+dapatkan_semua_satuan_didukung_oleh_sku()
}

class "Barang" as item {
+id: UUID
+nama: String
+id_ukuran_dasar: UUID
--
+tambah()
+update()
+hapus()
}

class "SKU" as sku {
+id: UUID
+barang_id: UUID
+sku: String
+nama_spesifikasi: String
+kuantitas: String
+price: Float
--
+tambah()
+update()
+hapus()
+tambahKonversi()
+updateKonversi()
+hapusKonversi()
}

class "Transaksi" as transaction {
+id: UUID
+tipe: String "Keluar/Masuk"
+pengguna_id: UUID
+penerima_id: UUID
+suplier: String
+division: String
+notes: String
+tanggal: Date
--
+tambah()
+cari()
+tambahItem()
}

class "Item Transaksi" as transactionItem {
+id: UUID
+transaksi_id: UUID
+sku_id: UUID
+satuan_id: UUID
+quantity: Integer
+base_quantity: Integer
+price: Float
---
-tambah()
}

class "Konversi Satuan Ukuran SKU" as skuMeasurementUnitConversion {
+id: UUID
+satuan_id: UUID
+sku_id: UUID
+konversi: Integer
--
-tambah()
-update()
-hapus()
}

class "Penerima" as recipient {
+id: UUID
+nama: String
+nama_panggilan: String
+divisi: String
--
+tambah()
+update()
+hapus()
}

class "Setting" as setting {
+id: UUID
+key: String
+value: String
--
+update()
}

' Relasi
role "1" -- "0..*" user : memiliki >
user "1" -- "0..*" transaction : membuat >

unit "1" -- "0..*" unit : satuan_dasar >
unit "1" -- "0..*" item : ukuran_dasar >
unit "1" -- "0..*" transactionItem : menggunakan >
unit "1" -- "0..*" skuMeasurementUnitConversion : dikonversi >

item "1" -- "0..*" sku : memiliki >

sku "1" -- "0..*" transactionItem : dijual/dibeli >
sku "1" -- "0..*" skuMeasurementUnitConversion : memiliki_konversi >

transaction "1" -- "0..*" transactionItem : berisi >
transaction "0..*" -- "0..1" recipient : diterima_oleh >

note left of setting
  Entity berdiri sendiri untuk 
  konfigurasi sistem global
  (misal: nama aplikasi, 
  format tanggal, dll)
end note

@enduml