---
title: A
config:
  theme: default
  layout: elk
---
erDiagram
    roles ||--o{ users : "diberikan ke"
    barang ||--o{ varian : "punya varian"
    varian ||--o{ item_aktifitas : "tercatat pada"
    satuan ||--o{ item_aktifitas : "mengukur"
    penerima ||--o{ aktifitas : "menerima"
    barang ||--|| satuan : "punya satuan terkecil"
    satuan ||--o{ satuan : "punya turunan"
    aktifitas ||--|{ item_aktifitas : "mengandung"
    konversi_satuan_varian }o--|| varian : "konversi untuk"
    konversi_satuan_varian }o--|| satuan : "konversi ke"
    users ||--o{ aktifitas : "dilakukan oleh"
    users ||--|{ sessions : "punya"

    roles {
        id VARCHAR(100) PK  "Id unik untuk role"
        nama VARCHAR(100) UK "Nama role: Admin Gudang, Super Admin, Unit Kerja"
    }

    notifications {
        id VARCHAR(100) PK "Id unik notification"
        type VARCHAR(100) "Tipe notifikasi"
        notifiable_id CHAR(64) "Reference id untuk polymorphic relation"
        notifiable_type VARCHAR(255) "Type untuk polymorphic relation"
        data TEXT "Data notifikasi berupa json"
        read_at TIMESTAMP "Tanggal notifikasi serta indikator telah dibaca"
        created_at TIMESTAMP "Tanggal notifikasi dicreate"
        updated_at TIMESTAMP "Tanggal notifikasi didelete"
    }

    sessions {
        id VARCHAR(100) PK
        user_id VARCHAR(100) FK
        ip_address VARCHAR(45)
        user_agent TEXT
        payload LONGTEXT
        last_activity INTEGER
    }

    users {
        id VARCHAR(100) PK "Id unik user"
        nama VARCHAR(255) "Nama user"
        username VARCHAR(255) UK "Username unik user"
        password VARCHAR(100) "Password rahasia untuk login"
        role_id VARCHAR(100) FK "Id role yang diberikan kepada pengguna"
        path_poto_profil VARCHAR(100) "Path ke file poto profil pengguna"
        created_at TIMESTAMP "Tanggal user dicreate"
        updated_at TIMESTAMP "Tanggal user diupdate"
        deleted_at TIMESTAMP "Tanggal user didelete, untuk indikator soft delete"
    }

    setting {
        id VARCHAR(100) PK
        icon_aplikasi VARCHAR(255)
        nama_aplikasi VARCHAR(255)
        nama_instansi VARCHAR(255)
        alamat_instansi VARCHAR(255)
        telepon_instansi VARCHAR(20)
        moto VARCHAR(255)
        visi_misi TEXT
        struktur_organisasi VARCHAR(255)
    }

    satuan {
        id VARCHAR(100) PK "Id unik satuan"
        nama VARCHAR(255) UK "Nama satuan"
        satuan_terkecil_id VARCHAR(100) FK "Relasi ke satuan terkecil"
        konversi INTEGER "Nilai konversi ke satuan terkecil"
        satuan_terkecil boolean "Indikator satuan terkecil atau turunan"
        created_at TIMESTAMP "Tanggal satuan dicreate"
        updated_at TIMESTAMP "Tanggal satuan diupdate"
        deleted_at TIMESTAMP "Tanggal satuan didelete, untuk indikator soft delete"
    } 

    penerima {
        id VARCHAR(100) PK "Id unik penerima"
        nama VARCHAR(255) "Nama penerima"
        nama_panggilan VARCHAR(255) "Nama panggilan penerima"
        unit_kerja VARCHAR(255) "Unit kerja dari penerima"
        created_at TIMESTAMP "Tanggal penerima dicreate"
        updated_at TIMESTAMP "Tanggal penerima diupdate"
        deleted_at TIMESTAMP "Tanggal penerima didelete, untuk indikator soft delete"
    }

    aktifitas {
        id VARCHAR(100) PK "Id unik dari aktifitas"
        tipe enum "Nilai: masuk/keluar, indikator tipe aktifitas" 
        user_id VARCHAR(100) FK "Foreign key ke tabel users"
        penerima_id VARCHAR(100) FK "Foreing key ke tabel penerima"
        penyuplai VARCHAR(255) "Nama penyuplai, Hanya untuk transaksi barang masuk"
        unit_kerja VARCHAR(255) "Nama unit kerja"
        tanggal date "Tanggal aktifitas"
        created_at TIMESTAMP "Tanggal aktifitas dicreate"
        updated_at TIMESTAMP "Tanggal aktifitas diupdate"
        deleted_at TIMESTAMP "Tanggal aktifitas didelete, untuk indikator soft delete"
    }

    item_aktifitas {
        id VARCHAR(100) PK "Id unik item_aktifitas"
        aktifitas_id VARCHAR(100) FK "Foreign key ke tabel aktifitas"
        varian_id VARCHAR(100) FK "Varian dari barang yang masuk dalam aktifitas"
        satuan_id VARCHAR(100) FK "Satuan aktifitas, bisa pakai satuan terkecil bisa tidak"
        kuantitas INTEGER "Jumlah dalam satuan yang digunakan dalam aktifitas"
        kutantitas_dasar INTEGER "Jumlah dalam satuan terkecil (sesudah konversi)"
        harga DECIMAL(22_4) "Harga per satuan saat aktifitas"
        created_at TIMESTAMP "Tanggal item_aktifitas dicreate"
        updated_at TIMESTAMP "Tanggal item_aktifitas diupdate"
        deleted_at TIMESTAMP "Tanggal item_aktifitas didelete, untuk indikator soft delete"
    }

    barang {
        id VARCHAR(100) PK "Id unikbarang"
        nama VARCHAR(100) UK "Nama barang"
        satuan_terkecil_id VARCHAR(100) FK "Satuan terkecil yang digunakan pada barang"
        created_at TIMESTAMP "Tanggal barang dicreate"
        updated_at TIMESTAMP "Tanggal barang diupdate"
        deleted_at TIMESTAMP "Tanggal barang didelete, untuk indikator soft delete"
    }

    varian {
        id VARCHAR(100) PK
        barang_id VARCHAR(100) FK
        kode_barang VARCHAR(100) UK "Kode SKU unik"
        nama_spesifikasi VARCHAR(255) "Merk/varian: Sidu, Paperline"
        stok INTEGER "Stok yang tersedia pada gundang"
        harga DECIMAL(22_4) "Harga barang pada varian"
        created_at TIMESTAMP "Tanggal user dicreate"
        updated_at TIMESTAMP "Tanggal user diupdate"
        deleted_at TIMESTAMP "Tanggal user didelete, untuk indikator soft delete"
    }

    konversi_satuan_varian {
        id VARCHAR(100) "Id unik konversi satuan varian"
        satuan_id VARCHAR(100) FK, UK "Id satuan pemilik konversi"
        varian_id VARCHAR(100) FK, UK "Foreign key ke varian"
        konversi INTEGER "Nilai konversi ke satuan terkecil"
        created_at TIMESTAMP "Tanggal konversi satuan dicreate"
        updated_at TIMESTAMP "Tanggal konversi satuan diupdate"
    }