@startuml usecase
left to right direction
skinparam linetype polyline

actor "Administrator" as admin
actor "Bendahara" as bendahara
actor "Petugas" as petugas
actor "Unit" as unit

rectangle "Aplikasi Manajemen ATK" {
    usecase "Mengelola Pengguna" as UC1
    usecase "Mengelola Satuan" as UC7
    usecase "Mengelola Barang" as UC3
    usecase "Meminta barang" as UC2
    usecase "Menerima permintaan barang" as UC6
    usecase "Laporan" as UC4
    usecase "Laporan Pengeluaran" as UC4_1
    usecase "Pengaturan Aplikasi" as UC5
}

' UC1 <-- admin
UC5 <-- admin
UC1 <-- admin
unit --> UC2
petugas --> UC7
petugas --> UC3
petugas --> UC6
petugas --> UC4
UC4_1 <-- bendahara

@enduml
