@startuml Kelola Barang
title Sequence Diagram - Kelola Barang

actor "Petugas" as actor1
participant "Halaman\nBarang" as barang
participant "Server" as sistem
database "Database" as db

actor1 -> barang: Membuka halaman barang
activate barang
barang -> sistem: Request data barang
activate sistem
sistem -> db: Query data barang
activate db
db --> sistem: Data barang
deactivate db
sistem --> barang: Data barang
deactivate sistem

actor1 -> barang: Lihat data barang

alt Tambah Barang
    actor1 -> barang: Input data barang baru
    barang -> sistem: Request tambah barang
    activate sistem
    sistem -> db: Insert data barang
    activate db
    db --> sistem: Data barang
    deactivate db
    sistem --> barang: Redirect kembali ke halaman barang
    deactivate sistem
    
else Ubah Barang
    actor1 -> barang: Input perubahan data barang
    barang -> sistem: Request update barang
    activate sistem
    sistem -> db: Update data barang
    activate db
    db --> sistem: Jumlah data terupdate
    deactivate db
    sistem --> barang: Redirect kembali ke halaman barang
    deactivate sistem
    
else Hapus Barang
    actor1 -> barang: Pilih data untuk dihapus
    barang -> sistem: Request hapus barang
    activate sistem
    sistem -> db: Delete data barang
    activate db
    db --> sistem: Jumlah data terhapus
    deactivate db
    sistem --> barang: Redirect kembali ke halaman barang
    deactivate sistem
end
deactivate barang
@enduml